modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "https://github.com/starfish-studios/Building-But-Better/blob/main/LICENSE"

[[mods]]
modId = "bbb"
version = "${version}"
displayName = "Building But Better"
authors = "Starfish Studios"
description = '''
A mod focused on adding new building blocks with customizability and interactions!\n\n§c§l§u§o! Pre-releases WILL be buggy ! §cPlease report any issues on our GitHub or Discord.\n\n§9§l§uCHANGELOG (2.0pre2)§7\n- Frames' code has been almost entirely redone; they no longer connect to non-solid blocks or blocks with smaller models.\n- Layers now have a rotate/mirror method -- this should allow them to properly save and load when put into structures. \n- Block descriptions now use "Left Control" instead of "Left Shift" to show their tooltips. I had noticed that when trying to fast-transfer them to containers you would sort of get flashbanged. \n- Fixed HangingEntityMixin - should now have a higher priority + survive while in Frames \n- Columns now have proper waterlogging - if their layers have not been removed, they can not be waterlogged. If their layers are replaced, they will lose any existing waterlogged state. \n- Added Hammer compatibility with Another Furniture. \n- Removed buggy "Paintings surviving in Frames" mechanic
'''
#logoFile = ""

[[dependencies.building_but_better]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.building_but_better]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.building_but_better]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
